# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Machine Learning
author: Sergio Silvera - Alvaro Romano - Miguel Cabrera
copyright: "2025"
logo: logo.png
# Auto-exclude files not in the toc
only_build_toc_files: True


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off
  cache                     : "" 
  timeout                   : 30 


# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_edit_page_button      : false
  use_issues_button: false
  use_repository_button: true
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
